require 'rubygems'
require 'rake/gempackagetask'
require 'rubygems/specification'
require 'date'
require 'rake'
require 'rake/testtask'
require 'rake/rdoctask'

GEM = "<%= name %>"
revision = `svn info`.match(/Revision: (\d+)/)[1] 
GEM_VERSION = "2.0.#{revision}"
AUTHOR = "Revolution Health"
EMAIL = "rails@revolutionhealth.com"
HOMEPAGE = "https://github.com/revolutionhealth"
SUMMARY = "A gem that provides..."

spec = Gem::Specification.new do |s|
  s.name = GEM
  s.version = GEM_VERSION
  s.platform = Gem::Platform::RUBY
  s.has_rdoc = true
  s.extra_rdoc_files = ["README", "LICENSE", 'TODO']
  s.summary = SUMMARY
  s.description = s.summary
  s.author = AUTHOR
  s.email = EMAIL
  s.homepage = HOMEPAGE
  
  # Uncomment this to add a dependency
  # s.add_dependency "foo"
  
  s.require_path = 'lib'
  s.autorequire = GEM
  s.files = %w(LICENSE README Rakefile TODO) + Dir.glob("{lib,specs}/**/*")
end

Rake::GemPackageTask.new(spec) do |pkg|
  pkg.gem_spec = spec
end

desc "install the gem locally"
task :install => [:package] do
  sh %{sudo gem install pkg/#{GEM}-#{GEM_VERSION}}
end

desc "create a gemspec file"
task :make_spec do
  File.open("#{GEM}.gemspec", "w") do |file|
    file.puts spec.to_ruby
  end
end


desc 'Default: run unit tests.'
task :default => :test

desc "Test the #{GEM} plugin."
Rake::TestTask.new(:test) do |t|
  t.libs << 'lib'
  t.pattern = ['test/*_test.rb', 'test/**/*_test.rb']
  t.verbose = true
end

desc "Generate documentation for the #{GEM} plugin."
Rake::RDocTask.new(:rdoc) do |rdoc|
  rdoc.rdoc_dir = 'rdoc'
  rdoc.title    = GEM
  rdoc.options << '--line-numbers' << '--inline-source'
  rdoc.rdoc_files.include('README')
  rdoc.rdoc_files.include('lib/**/*.rb')
end
